### PR TITLE
Revert 01db9ca51d3fb595a89a182f1645faafc1a8997e

### PR DESCRIPTION
**Pull request by ExtremeDude2**
Reverts ExtremeDude2/cmd-calculator#6

### CODE REVIEW

**Comment by cxd4** [comment]
y u no merge?!?!!

**Comment by ExtremeDude2** [comment]
Couldn't decide.

**Comment by cxd4** [comment]
octagonvshexagon.avi

Maybe that will help.

**Comment by cxd4** [comment]
so i herd u liek merge conflicts?

**Comment by ExtremeDude2** [comment]
ner

**Pull request closed without merging**
